### ISSUE TITLE
Add CI to Nirjas

### ISSUE THREAD

**Issue by hastagAB** [fossology/Nirjas#12]
# Description

- Add CI for Nirjas.
- Installation and script for Python and C++ only (Both are major languages & covers most of the comment syntax structure)
- Ignore adding CI for the test at this moment (test script need further enhancement with respect to extractor algorithms.)

**Comment by GMishx** [comment]
I do not understand the second point. What do you mean by script for Python and C++?

However, I have created PR #13 with the test cases. If it feels okay to you, please attach the issue to the PR.

**Comment by hastagAB** [comment]
> I do not understand the second point. What do you mean by script for Python and C++?
> 
> However, I have created PR #13 with the test cases. If it feels okay to you, please attach the issue to the PR.

I meant if possible, a test could run something like `nirjas -p <python file>` and  `nirjas -p <cpp file>` to check if both commands are working fine or not. Because if these two languages work fine, then most of the other language should work too.
