### ISSUE TITLE
Wrong comment captures

### ISSUE THREAD

**Issue by GMishx** [fossology/Nirjas#14]
Nirjas currently gets confused if the comment is something like `/*********/` or `/* <comment> */` in C.

For example, following were marked as comments:
1. https://github.com/xdebug/xdebug/blob/192aba841a6332b09b475fa3926a5c5a6edf3071/src/lib/var.c#L177-L203
2. https://github.com/xdebug/xdebug/blob/192aba841a6332b09b475fa3926a5c5a6edf3071/src/lib/var.c#L201-L207 (the comment captured was `" ** Data returning functions "`)
3. https://github.com/xdebug/xdebug/blob/192aba841a6332b09b475fa3926a5c5a6edf3071/src/lib/var.c#L205-L1018
4. https://github.com/xdebug/xdebug/blob/192aba841a6332b09b475fa3926a5c5a6edf3071/src/lib/var.c#L352-L1054 (captured `" ** XML encoding function ")
5. https://github.com/xdebug/xdebug/blob/192aba841a6332b09b475fa3926a5c5a6edf3071/src/lib/var.c#L365-L1131

Also, `http://` is marked as single line comment:
1. https://github.com/xdebug/xdebug/blob/192aba841a6332b09b475fa3926a5c5a6edf3071/src/lib/var.c#L10 (captured `"/xdebug.org/license.php"`)
2. https://github.com/xdebug/xdebug/blob/192aba841a6332b09b475fa3926a5c5a6edf3071/src/lib/var.c#L1158 (captured `"/www.php.net/"`)

**Comment by codeakki** [comment]
May i work on this issue! Im a newbie nd want to contribute in fossology
