### ISSUE TITLE
Adding support for new languages

### ISSUE THREAD

**Issue by Aman-Codes** [fossology/Nirjas#18]
Add support for new languages in Nirjas. Some commonly used languages (or file type) whose support can be added
- [x] Typescript (.ts) https://github.com/fossology/Nirjas/pull/19
- [x] Dart (.dart) https://github.com/fossology/Nirjas/pull/24
- [ ] Scss  (.scss)
- [x] React js (.jsx) https://github.com/fossology/Nirjas/pull/21
- [x] Tsx (.tsx) https://github.com/fossology/Nirjas/pull/23
I would like to work on it. Being a first time contributor to fossology, it would be helpful if you could guide me

**Comment by Kaushl2208** [comment]
Hey @Aman-Codes , Yes support of these languages will be of great help. Have you started going through the code? Do tell me how can I help you out here.

**Comment by Aman-Codes** [comment]
Yes I am currently going through code to understand its working. I will do let you know if I face any difficulties and will send a pull request shortly.

**Comment by Aman-Codes** [comment]
Hi @Kaushl2208 
I have a query should I take into account the documentation comments separately from normal comment in sass and dart ?
For example: 
// This is a general comment 
/// This is a documentation comment

Reference [Dart](https://www.w3adda.com/dart-tutorial/dart-comments) [Sass](https://sass-lang.com/documentation/syntax/comments)

**Comment by hastagAB** [comment]
@Aman-Codes you can take both as single line comment.

**Comment by Aman-Codes** [comment]
Ok thanks @hastagAB

**Comment by GMishx** [comment]
Wow! Almost all the languages as in! Once we have the `scss`, we can do a release.

**Comment by Aman-Codes** [comment]
@GMishx Yeah I will make a pull request for it by today
