### ISSUE TITLE
Comment terminates on special character

### ISSUE THREAD

**Issue by Aman-Codes** [fossology/Nirjas#27]
# Description
Nirjas terminates the comment on occurrence of any special character out of !$%&{}~`"'| for all languages

# How to Test
Create a c file and add a single line comment which contains any special character out of  !$%&{}~`"'|

# How to Resolve
Changing regex from `(\/\/\s*[\w #\.()@+-_*\d]*)` to `(\/\/\s*[\w #\.()@!-~*\d]*)`

**Comment by GMishx** [comment]
I am currently working on it. I changed the regex from list of acceptable characters to a simple `.*`

Will have to test if it fails somewhere.

**Comment by Aman-Codes** [comment]
> I am currently working on it. I changed the regex from list of acceptable characters to a simple `.*`
Sounds good

**Comment by codeakki** [comment]
May i work on this issue I'm a newbie nd want to explore how open source community works nd want to implement my learning skiils

**Comment by GMishx** [comment]
Thanks for your interest @codeakki but #28 already solves it.

**Comment by codeakki** [comment]
@GMishx sir is thier is anything where i start my contribution in these project or organisation for ne

**Comment by codeakki** [comment]
sir, i want to contribute in fossology organization can u guide me
little bit.

**Comment by hastagAB** [comment]
Hi @codeakki, You can start with these:

[`Good first issues` in FOSSology]
- https://github.com/fossology/fossology/labels/good%20first%20issue

[Open issues in Atarashi]
- https://github.com/fossology/atarashi/issues/66

Currently `Nirjas` has no unattended issues open but you can explore the project to find some.

**Comment by GMishx** [comment]
Thanks for the inputs @hastagAB . I have just created another issue https://github.com/fossology/atarashi/issues/77 and would like to add it to your list.
