### ISSUE TITLE
Need Support For SQL

### ISSUE THREAD

**Issue by Kaushl2208** [fossology/Nirjas#37]
As a code comment extractor, We are planning to increase our reach to preferred programming languages world wide. We need support for SQL.

For getting started you can refer to [CONTRIBUTING.md](https://github.com/fossology/Nirjas/blob/master/CONTRIBUTING.md)

**Comment by Kaushl2208** [comment]
Hey @noobkid2411 , Thankyou for your interest. I have assigned the same to you. 👍

**Comment by GMishx** [comment]
Changes merged with #55
