### ISSUE TITLE
Code Formatting and Linting is required.

### ISSUE THREAD

**Issue by Kaushl2208** [fossology/Nirjas#39]
Currently, Nirjas codebase is not following any specific Linters and formatters. Having a linter is useful for uniformity in coding style.

### What to do?
- [ ] Either Flake8 or Pylint can be introduced as a linter.
- [ ] Separate code linting stage can be introduced in CI pipeline.

**Comment by thevectorguy** [comment]
Hey , I can contribute to this issue. It would be probably my first contribution and I'll like to work on this.
